### ISSUE TITLE
Failure to decompound Wandhalter 

### ISSUE THREAD

**Issue by felixbarny** [jprante/elasticsearch-analysis-decompound#38]
The term `Wandhalterung` is split to the tokens `wand`, `alterung` instead of `wand`, `halterung`. When setting the threshold to `0.63` or higher, the tokens are `wandh` and `alterung`. What can I do to fix this?

These are my settings:

```yaml
index :
    analysis :
        analyzer :
            analyzer_decomp :
                type : custom
                tokenizer : standard
                filter : [lowercase, decomp]
        filter :
            decomp:
                type: decompound
        tokenizer:
            decomp:
                type: standard
                filter:
                  - decomp
```

I'm using Elasticsearch 2.1.1 and elasticsearch-analysis-decompound 2.1.1.0

**Comment by felixbarny** [comment]
Interestingly, when adding `Wandhalter` to `org.xbib.elasticsearch.analysis.decompound.DecompounderTests`, the term is correctly split to `[Wand, halter]`.

**Comment by felixbarny** [comment]
I've kind of solved this by applying a stemmer before the `decomp` filter:

```yaml
index :
    analysis :
        analyzer :
            analyzer_decomp :
                type : custom
                tokenizer : standard
                filter : [lowercase, snow_de, decomp]
        filter :
            decomp:
                type: decompound
            snow_de :
                type : snowball
                language : German2
        tokenizer:
            decomp:
                type: standard
                filter:
                  - decomp
```
