### ISSUE TITLE
German decomp adds ";" symbol for certain words

### ISSUE THREAD

**Issue by fterrier** [jprante/elasticsearch-analysis-decompound#4]
Configuration: 

```
default:
  tokenizer: standard
  filter: [german_decomp]

german_decomp:
  type: decompound
```

Query: _analyze?text="tomaten"

Result: 

```
{
  tokens: [
  {
    token: tomaten
    start_offset: 1
    end_offset: 8
    type: <ALPHANUM>
    position: 1
  }
  {
    token: ;
    start_offset: 1
    end_offset: 2
    type: <ALPHANUM>
    position: 1
  }
  ]
}
```
